export const lootTables = {
  drops: [
    { id: 'scrap_plate', rarity: 'common', stat: 'maxHp', value: 14 },
    { id: 'keen_edge', rarity: 'common', stat: 'attack', value: 3 },
    { id: 'sparking_wire', rarity: 'common', stat: 'energyRegen', value: 1.2 },
    { id: 'sturdy_boots', rarity: 'common', stat: 'defense', value: 2 },
    { id: 'precision_glass', rarity: 'common', stat: 'critChance', value: 0.01 },
    { id: 'copper_core', rarity: 'common', stat: 'maxEnergy', value: 8 },
    { id: 'ash_wrap', rarity: 'uncommon', stat: 'burnPower', value: 0.14 },
    { id: 'frost_thread', rarity: 'uncommon', stat: 'freezePower', value: 0.13 },
    { id: 'shock_coil', rarity: 'uncommon', stat: 'shockPower', value: 0.16 },
    { id: 'hemorrhage_pin', rarity: 'uncommon', stat: 'bleedPower', value: 0.17 },
    { id: 'dash_spur', rarity: 'uncommon', stat: 'moveSpeed', value: 18 },
    { id: 'recovery_foam', rarity: 'uncommon', stat: 'hpRegen', value: 0.9 },
    { id: 'sigil_lens', rarity: 'rare', stat: 'critMultiplier', value: 0.2 },
    { id: 'arcane_circuit', rarity: 'rare', stat: 'skillDamage', value: 0.16 },
    { id: 'combo_link', rarity: 'rare', stat: 'comboDecay', value: -140 },
    { id: 'vamp_emblem', rarity: 'rare', stat: 'lifesteal', value: 0.04 },
    { id: 'adaptive_mesh', rarity: 'rare', stat: 'allRes', value: 0.05 },
    { id: 'overclock_chip', rarity: 'rare', stat: 'cooldownReduction', value: 0.08 },
    { id: 'void_reservoir', rarity: 'epic', stat: 'maxEnergy', value: 24 },
    { id: 'warcore', rarity: 'epic', stat: 'attack', value: 11 },
    { id: 'bulwark_heart', rarity: 'epic', stat: 'defense', value: 7 },
    { id: 'phase_shroud', rarity: 'epic', stat: 'iFrameBonusMs', value: 90 },
    { id: 'glacial_brand', rarity: 'epic', stat: 'freezeFullChance', value: 0.16 },
    { id: 'inferno_mark', rarity: 'epic', stat: 'burnStackCap', value: 2 },
    { id: 'tempest_matrix', rarity: 'legendary', stat: 'shockChainExtra', value: 2 },
    { id: 'execution_relay', rarity: 'legendary', stat: 'executeBonus', value: 0.08 },
    { id: 'eternal_blade', rarity: 'legendary', stat: 'attack', value: 22 },
    { id: 'time_fracture', rarity: 'legendary', stat: 'cooldownReduction', value: 0.15 },
    { id: 'phoenix_cell', rarity: 'legendary', stat: 'revive', value: 1 },
    { id: 'oracle_eye', rarity: 'legendary', stat: 'critChance', value: 0.06 },
  ],
  rarityWeight: {
    common: 58,
    uncommon: 24,
    rare: 11,
    epic: 5,
    legendary: 2
  }
};
