export const talents = [
  { id:'edge_1', name:'Razor Edge', desc:'+8% light attack damage', tags:['offense'] },
  { id:'edge_2', name:'Relentless Edge', desc:'+12% heavy attack damage', tags:['offense'] },
  { id:'focus_1', name:'Battle Focus', desc:'+15 max energy', tags:['resource'] },
  { id:'focus_2', name:'Reservoir', desc:'+0.8 energy/sec regen', tags:['resource'] },
  { id:'aegis_1', name:'Iron Skin', desc:'+12 defense', tags:['defense'] },
  { id:'aegis_2', name:'Last Stand', desc:'-18% damage below 35% HP', tags:['defense'] },
  { id:'tempo_1', name:'Swift String', desc:'+10% combo speed', tags:['combo'] },
  { id:'tempo_2', name:'Break Rhythm', desc:'3rd combo hit applies bleed', tags:['combo','bleed'] },
  { id:'arc_1', name:'Arc Conductor', desc:'+20% shock duration', tags:['shock'] },
  { id:'arc_2', name:'Discharge', desc:'shock deals +22% chain damage', tags:['shock'] },
  { id:'frost_1', name:'Cold Intent', desc:'+18% freeze slow power', tags:['freeze'] },
  { id:'frost_2', name:'Rime Lock', desc:'+10% full freeze chance', tags:['freeze'] },
  { id:'pyre_1', name:'Smolder', desc:'+25% burn DoT', tags:['burn'] },
  { id:'pyre_2', name:'Kindling', desc:'burn refresh adds 1 stack chance', tags:['burn'] },
  { id:'void_1', name:'Rift Step', desc:'Shadow Step +26 range', tags:['shadowStep'] },
  { id:'void_2', name:'Echo Step', desc:'Shadow Step afterimage +60% damage', tags:['shadowStep'] },
  { id:'prism_1', name:'Shatter Prism', desc:'Freezing Prism cone +14%', tags:['freezingPrism'] },
  { id:'prism_2', name:'Cryo Lance', desc:'Freezing Prism damage +18%', tags:['freezingPrism'] },
  { id:'rupture_1', name:'Sky Cutter', desc:'Ascending Rupture range +20%', tags:['ascendingRupture'] },
  { id:'rupture_2', name:'Aerial Judge', desc:'Ascending Rupture crit +15%', tags:['ascendingRupture'] },
  { id:'core_1', name:'Unstable Core', desc:'Overload Core base +25%', tags:['overloadCore'] },
  { id:'core_2', name:'Execution Loop', desc:'Overload execute threshold +8%', tags:['overloadCore'] },
  { id:'blade_1', name:'Surging Flow', desc:'Flow Blade +1 hit', tags:['flowBlade'] },
  { id:'blade_2', name:'Hemorrhage Arc', desc:'Flow Blade applies bleed', tags:['flowBlade','bleed'] },
];

export const talentSynergies = [
  ['tempo_2','blade_2','Bleed ticks gain +40% from combo count'],
  ['arc_1','core_1','Overload detonation shocks nearby enemies'],
  ['frost_1','prism_1','Frozen targets take +16% heavy damage'],
  ['void_1','void_2','Shadow Step leaves damaging echo'],
  ['rupture_1','rupture_2','Ascending Rupture guarantees crit on shocked enemies'],
  ['pyre_1','pyre_2','Burn max stacks +1 and refresh extends duration'],
  ['aegis_1','aegis_2','Gain 20 shield when dropping below 35% hp'],
  ['focus_1','focus_2','Energy cap bonus also grants +5% skill haste'],
];
